environment:
  cookie_root_domain: .prod.monitalks.io
  gateway: https://openfaas.prod.monitalks.io
  internal_gateway: http://openfaas.default.svc.cluster.local:8080/function
  websocket_server_url: https://ws.social.monitalks.io
  origin: "https://openfaas.prod.monitalks.io,https://social.prod.monitalks.io"
