environment:
  base_route: /storage
  bucket_name: storage-kube-monitalks-io
  exec_timeout: "180"
  write_timeout: "180"
  read_timeout: "180"
  storage_secret_path: /var/openfaas/secrets/serviceAccountKey.json
  write_debug: "true"
