environment:
  base_route: /storage
  bucket_name: monisocial-20a8b.appspot.com
  exec_timeout: "180"
  read_timeout: "180"
  storage_secret_path: /var/openfaas/secrets/serviceAccountKey.json
  write_debug: "true"
  write_timeout: "180"
